name: Build and Push Add-on

permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:  # Manual only - use build-and-push.sh for local builds

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64, amd64]
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version
        id: version
        run: |
          VERSION=$(grep '^version:' piper-yang/config.yaml | awk '{print $2}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set registry owner (lowercase)
        run: |
          echo "REGISTRY_OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./piper-yang
          file: ./piper-yang/Dockerfile
          platforms: linux/${{ matrix.arch }}
          build-args: |
            BUILD_FROM=ghcr.io/home-assistant/${{ matrix.arch }}-base-debian:bookworm
            BUILD_ARCH=${{ matrix.arch }}
            WYOMING_PIPER_VERSION=2.2.2
          push: true
          tags: |
            ghcr.io/${{ env.REGISTRY_OWNER }}/${{ matrix.arch }}-addon-piper-yang:${{ steps.version.outputs.version }}
            ghcr.io/${{ env.REGISTRY_OWNER }}/${{ matrix.arch }}-addon-piper-yang:latest
